[package]
name = "esi_example_minimal"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[dependencies]
fastly = "^0.10"
esi = { path = "../../esi" }
log = "^0.4"
env_logger = "^0.11"
