[package]
name = "esi_example_minimal"
version = "0.4.1"
authors = ["Kailan Blanks <kailan@enviark.com>"]
edition = "2018"
publish = false

[dependencies]
fastly = "^0.10"
esi = { path = "../../esi" }
log = "^0.4"
env_logger = "^0.11"
