[package]
name = "esi_example_app"
version = "0.4.0-pre2"
authors = ["Kailan Blanks <kailan@enviark.com>"]
edition = "2018"
publish = false

[dependencies]
fastly = "^0.9"
esi = { path = "../esi" }
log = "^0.4"
env_logger = "0.10.0"
