# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["kailan@enviark.com"]
description = ""
language = "rust"
manifest_version = 2
name = "esi_example_app"
service_id = "7Oyrwb6dUr5ISWCcDess2Z"

[local_server]

  [local_server.backends]

    [local_server.backends.mock-s3]
      url = "https://mock-s3.edgecompute.app"

[scripts]
  build = "cargo build --bin esi_example_app --release --target wasm32-wasi --color always"

[setup]

  [setup.backends]

    [setup.backends.mock-s3]
      address = "mock-s3.edgecompute.app"
      port = 443
