on: push
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup show
          rustup component add rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check
        shell: bash
      - name: Check source
        run: cargo check
        shell: bash
      - name: Install Compute local testing server
        run: cargo install viceroy
        shell: bash
      - name: Run tests
        run: cargo test
        shell: bash
